name: Docker Image CI 

on:
  push

jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
    runs-on: ubuntu-latest
    steps:
      # checkout codebase
      - uses: actions/checkout@v4
      # login, build, and push to ghcr
      - name: Docker build
        uses: mr-smithers-excellent/docker-build-push@v5
        id: build
        with:
          image: ${{ env.IMAGENAME }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # now use the new image to deploy our instance
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: canal-money/lndhub-deployment
          path: infra
          token: ${{ secrets.PAT }}
      # deploy regtest
      - name: Update dev environment
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: fjogeleit/yaml-update-action@v0.7.0
        with:
          valueFile: 'regtest.json'
          propertyPath: 'lndhub.version'
          value: ${{ steps.build.outputs.tags }}
          repository: canal-money/lndhub-deployment
          branch: main
          commitChange: true
          message: 'CD: Update lndhub tag to ${{ steps.build.outputs.tags }}'
          token: ${{ secrets.PAT }}
          workDir: infra
